source 'http://rubygems.org'

gem 'httparty', '~> 0.15.6'
gem 'autorun', '~> 0.1.0'
gem 'minitest'
gem 'json'
gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'rake'
gem 'pry'
gem 'site_prism', '~> 2.9'
gem 'rspec-rails', '~> 3.0.0'
gem 'libxml-ruby', '~> 3.0'
gem 'nokogiri', '~> 1.8'
gem 'utils', '~> 0.9.0'
gem 'roo'
gem 'to_xml', '~> 0.1.1'
gem 'mysql2'
gem 'site_prism', '~> 2.9'